### ISSUE TITLE
Cannot download `input_datasets.zip`. This repository is over its data quota (Git LFS)

### ISSUE THREAD

**Issue by fmease** [casperboone/dltpy#27]
Trying to `git clone` this repository with [Git Large File Storage (LFS)](https://git-lfs.github.com/) installed or attempting to `git lfs pull`, results in the following error (line breaks added for readability):

```
Error downloading object: input_datasets.zip (e2499dd):
Smudge error: Error downloading input_datasets.zip
(e2499dd32d778190d8259c2d9fd27743a163effcc5f2175a94faf88681e030f8):
batch response:
This repository is over its data quota.
Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

According to [GitHub's documentation about billing for Git LFS](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-git-large-file-storage)

> Every account using Git Large File Storage receives 1 GB of free storage and 1 GB a month of free bandwidth

At the time of this writing it is 2021-01-08 – basically the start of the month – and so it is very surprising to me that the 1GB of bandwidth is already used up.

Is it possible that I can gain access to `input_datasets.zip` without needing to wait until the end of the month when it is not even clear if the file will be accessible at that point in time? Either by increasing the quota or by giving me a link to a mirror site? I would be very thankful for this.

P.S: I, León Liehr, already got in touch with @casperboone concerning other matters.

**Comment by casperboone** [comment]
Hi @fmease,

I emailed a download link to you. It's the "quota" of my personal account that's being used up after pretty much 1 download since the file is 700MB 😅 .

**Comment by fmease** [comment]
I see \^\^! Thank you very much!
